# Setup
title:               CHEN Junhao
tagline:             '陈俊豪'
description:         "CHEN Junhao's Personal Page" # 'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://chenjunhaoBU.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              CHEN Junhao
  url:               https://twitter.com/Forrest_CJ
  email:             chenjh@bu.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
